### ISSUE TITLE
 Extend your payment options with Mollie Plus.

### ISSUE THREAD

**Issue by wmdhosting** [white-nl/commerce-mollie-plus#13]
**Extend your payment options with Mollie Plus.**  

Is this just  marketing slogan..  or its posiblle to add new payment providers 

Like with some other plugins-- Postie  for shipping from Verbb

**Comment by WHITE-developer** [comment]
Hi @wmdhosting,
With the Mollie Plus plugin you can enable all the listed payment methods.
It's not possible to use different payment methods/providers as listed.
