### ISSUE TITLE
Plans for Craft 5?

### ISSUE THREAD

**Issue by kevinmu17** [white-nl/commerce-mollie-plus#24]
### Description
Hi guys, are there any plans/ETA's for Craft 5 support?

**Comment by Romanavr** [comment]
Same question. Any ETA?

**Comment by white-lukas** [comment]
Hi @kevinmu17 , @Romanavr 
We have it planned for 17/06

**Comment by boboldehampsink** [comment]
Hi guys, any updates on this?

**Comment by white-lukas** [comment]
@kevinmu17 @Romanavr @boboldehampsink , just tagged [3.0.0](https://github.com/white-nl/commerce-mollie-plus/releases/tag/3.0.0) with craft 5 support
