### ISSUE TITLE
Catch 422 user errors

### ISSUE THREAD

**Issue by gijsstegehuis** [white-nl/commerce-mollie-plus#25]
### Description
End-user errors are now being reported as exceptions.
`The order is not accepted by Klarna. Please use another payment method`

Please add handling for this.

### Additional info

- Craft version: Craft Pro 4.9.5
- PHP version: 8.3.5
- Database driver & version: -
- Plugins & versions: -

**Comment by WHITE-developer** [comment]
Hey,
Is the order within the limits of Klarna,
You can make sure to show the customer only payment methods that match his order by adding some extra params to the `fetchPaymentMethods()` eg.
```twig
{% set paymentMethods = gateway.fetchPaymentMethods({
  'locale': cart.orderLanguage,
  'amount': cart.total,
  'currency': cart.paymentCurrency,
  'billingCountry': cart.billingAddress.countryCode,
}) %}
```

**Comment by gijsstegehuis** [comment]
Hi. We are already sending those along.
It doesn't seem to make a difference in this case.

It's probably going to be hard to catch all user errors this way.
Maybe this specific user got banned.

**Comment by WHITE-developer** [comment]
Do you have access to the Mollie dashboard, in that case there might be extra info about the reason,

Don't think there is more we can do than returning the error?

**Comment by gijsstegehuis** [comment]
Got another one today.

```
Client error: `POST https://api.mollie.com/v2/orders` resulted in a `422 Unprocessable Entity` response:
{"status":422,"title":"Unprocessable Entity","detail":"The 'billingAddress.familyName' field contains characters that ar...
```

I don't think the plugin should report any error when the response code is 422 and contains a `field`. 
see: https://docs.mollie.com/overview/handling-errors#id4
In this case it would always be a user error.

I didn't find any details in the Mollie dashboard btw.

**Comment by WHITE-developer** [comment]
Why wouldn't we need to report the error when it happens, we can't handle it as a success? 
In this case the order indeed won't be visible inside Mollie, as by the error it is not possible to create the order in Mollie.

**Comment by gijsstegehuis** [comment]
That's right. You can't handle it as a success, but you can safely suppress it.
There's nothing we (or you as a plugin developer) can do to fix it.

The user will be shown an error page right? they have got to fix it themselves.

**Comment by white-lukas** [comment]
The best solution is to catch the error earlier in the checkout process when the customer fills in his address, so that he gets a validation error there when he didn't fill in his full name
