### ISSUE TITLE
Questions regarding Twint

### ISSUE THREAD

**Issue by asands1** [white-nl/commerce-mollie-plus#26]
Hello!

One of our shared customers (Könitz Porzellan GmbH) is not seeing TWINT appear in their checkout while using the commerce-mollie-plus plug-in. 

As I haven't seen any any updates in latest releases, could you please give us more information if this payment is available for the plug-in and if not if there are plans to include TWINT in future releases? 

More information about this payment method can be found in our docs: https://docs.mollie.com/docs/twint

Kind regards,

**Comment by white-lukas** [comment]
Hi @asands1,

If the payment method is activated in his Mollie account it should show up, there are no changes necessary in the plugin to make this method available.
