### ISSUE TITLE
Unable to pake a payment when discount has applied for the order line item

### ISSUE THREAD

**Issue by nikolenko-dmitriy** [white-nl/commerce-mollie-plus#4]

**Comment by nikolenko-dmitriy** [comment]
We have the situation when order cannot be paid because of the error: 
```
Order line 1 is invalid. VAT amount is off. Expected VAT amount t (truncated...)\n
```
Here is the full response from Mollie [2022-02-03_18-41](https://user-images.githubusercontent.com/65535954/152387762-9d50ba2c-03de-4112-93f6-1e71257c5f64.png)

This order has only 1 line item with quantity 35 and the applied discount.
 
After some investigation we found that this happens when because of the `discount`: [2022-02-03_18-29](https://user-images.githubusercontent.com/65535954/152388214-c12ca2d7-ac77-4019-9481-7ea39ac93d61.png)

A dump of the result of the method `getItemListForOrder` contains this: [2022-02-03_18-33](https://user-images.githubusercontent.com/65535954/152388395-085f9fcd-4e63-4c96-bb0c-f5d784048435.png)

As you can see, the discount was added as a separate line item, because it's an `order adjuster`.

Afterwards we tried to disable the discount: [2022-02-03_18-32](https://user-images.githubusercontent.com/65535954/152388649-1b13fcf7-c81f-42c2-aabd-f11494608072.png) and error from Mollie wasn't triggered anymore.

Also there are no extra items in the result of the method `getItemListForOrder` when discount is disabled [2022-02-03_18-29_1](https://user-images.githubusercontent.com/65535954/152388806-5288dbea-48fe-42e7-8551-11384beb8f70.png) 

It makes me think that in case the discount is applied the `vatAmout` is calculated by the wrong formula, But I didn't find yet the exact reason.

Also there are some suggestions regarding discounts:
1. Can we avoid discounts to be added as separate line items for the order in Mollie? Probably it's better to use `discountAmount` property on the `lines` array? 
2. Or if we still need a separate order line, maybe we should split up lines with a parameter `"type": "physical"` and `"type": "discount"`, like in the example in [docs](https://docs.mollie.com/orders/handling-discounts#discounts-and-vouchers)

**Comment by WHITE-developer** [comment]
Hey @nikolenko-dmitriy ,
Sorry for the late reaction. 
We just released a new version where the lineItem discount is added as the `discountAmount`.
