### ISSUE TITLE
Allow customization payload that's been sent to Mollie

### ISSUE THREAD

**Issue by lenvanessen** [white-nl/commerce-mollie-plus#7]
With a simple event, developers can hook-into the plug-in to change certain fields. As an example, For us, it's much easier to match the actual order ID, rather than the order number that's passed to Mollie by default when then accountant is processing the payments in the Exact. With the changes in the pull request 8 we can do such customization, and more if needed. For instance, if to add extra comments, change address fields if we use non-standard ones.

**Comment by WHITE-developer** [comment]
closed by https://github.com/white-nl/commerce-mollie-plus/pull/8
