### ISSUE TITLE
Orders with other tax rate have incorrect unit prices in the resulting Mollie order

### ISSUE THREAD

**Issue by rbrv** [white-nl/commerce-mollie-plus#9]
### Description

We have set up 2 Tax Zones and 2 Tax Rates in Craft commerce

![Screenshot 2022-06-02 at 11 22 47](https://user-images.githubusercontent.com/43676281/171599234-4f98ae4d-f9c0-4742-b88e-267e50d70e73.png)

This enables us to have:
- 21% VAT for all NL orders, business or non business
- 21% VAT for all non-business EU orders
- 0% VAT for all business EU orders with a valid EU VAT Tax ID

### Example
- A product costs 242 EUR (including 21% VAT)
- There is a 50%-off promo, resulting in a new product price of 121 EUR (including 21% VAT)
- When ordering this product, 
  - the unit price is is incorrectly marked as 142 EUR, 
  -  21% NL VAT is removed and 21% EU VAT is added. [This removal of Tax is marked in Craft as a discount.](https://github.com/craftcms/commerce/blob/4.1/src/adjusters/Tax.php#L155)

Craft commerce order | Mollie order
--- | ---
![2022-06-02_11-03_2](https://user-images.githubusercontent.com/43676281/171598138-78026588-820e-4075-b8f6-0fc18661a4aa.png) | ![2022-06-02_11-03_1_2](https://user-images.githubusercontent.com/43676281/171597942-dd9b29cf-0f89-4c5a-95fd-a35b1cc0f668.png)

### Additional info
Latest Craft 3 and Craft Commerce 3 and latest Mollie plus plugin voor Craft Commerce 3

**Comment by WHITE-developer** [comment]
Hi @rbrv,
The unit price in Mollie should be `The price of a single item including VAT in the order line.`. In your case that is €121+€21 = €142, After that the discount of €21 is applied.
In the discount adjuster Craft isn't adding any data that it is a discount applied by a negative tax adjuster, so we have now way of ignoring this.

But if I see correctly, all your prices in Craft are already included VAT?
Then if you would remove the `Remove from price` on your `21% NL tax rate` and add the `Include in price` on your `21% EU tax rate`, then for this order you would only get 1 adjuster what would be a tax adjuster for 21% EU included.
If you would have a EU order with valid Tax ID you would only get 1 adjuster what would be a discount adjuster that would remove 21% VAT

An example from on of our shops:
|VAT Settings|Non business EU order|Business order with valid Tax ID|NL order|
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/22771556/171605310-3a84a89f-c37d-4785-9638-481a2439f7f3.png)|![image](https://user-images.githubusercontent.com/22771556/171605596-3c3ff612-18e9-4bbd-9e7e-8c0f89b5e3af.png)|![image](https://user-images.githubusercontent.com/22771556/171605793-a72b2c8d-5e93-4747-8a7f-60e32c607c25.png)|![image](https://user-images.githubusercontent.com/22771556/171605919-e0c2eab7-e393-4f04-8ada-1754ffacfe5d.png)|

**Comment by rbrv** [comment]
@WHITE-developer I've just implemented your suggestions, and it's working brilliantly! Thanks!
